# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ms_recursos_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# UUID support
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true