spring:
  application:
    name: ms-recursos
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ms_recursos_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:admin}
    password: ${DB_PASS:admin}
  jpa:
    hibernate:
      ddl-auto: update   # en dev
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    tu.paquete: DEBUG
