spring:
  application:
    name: ms-logistica

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/ms_recursos_db} # Usar SPRING_DATASOURCE_URL y el nombre 'postgres' como fallback.
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://keycloak:8080/realms/tpi/protocol/openid-connect/certs}

server:
  port: 8083

logging:
  level:
    org.hibernate.SQL: debug
